# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from stream.v1 import stream_pb2 as stream_dot_v1_dot_stream__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in stream/v1/stream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EchoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EchoClientStream = channel.stream_unary(
                '/api.stream.v1.EchoService/EchoClientStream',
                request_serializer=stream_dot_v1_dot_stream__pb2.EchoRequest.SerializeToString,
                response_deserializer=stream_dot_v1_dot_stream__pb2.EchoResponse.FromString,
                _registered_method=True)
        self.EchoServerStream = channel.unary_stream(
                '/api.stream.v1.EchoService/EchoServerStream',
                request_serializer=stream_dot_v1_dot_stream__pb2.EchoRequest.SerializeToString,
                response_deserializer=stream_dot_v1_dot_stream__pb2.EchoResponse.FromString,
                _registered_method=True)
        self.EchoBidirectionalStreamSync = channel.stream_stream(
                '/api.stream.v1.EchoService/EchoBidirectionalStreamSync',
                request_serializer=stream_dot_v1_dot_stream__pb2.EchoRequest.SerializeToString,
                response_deserializer=stream_dot_v1_dot_stream__pb2.EchoResponse.FromString,
                _registered_method=True)
        self.EchoBidirectionalStreamAsync = channel.stream_stream(
                '/api.stream.v1.EchoService/EchoBidirectionalStreamAsync',
                request_serializer=stream_dot_v1_dot_stream__pb2.EchoRequest.SerializeToString,
                response_deserializer=stream_dot_v1_dot_stream__pb2.EchoResponse.FromString,
                _registered_method=True)


class EchoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EchoClientStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EchoServerStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EchoBidirectionalStreamSync(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EchoBidirectionalStreamAsync(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EchoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EchoClientStream': grpc.stream_unary_rpc_method_handler(
                    servicer.EchoClientStream,
                    request_deserializer=stream_dot_v1_dot_stream__pb2.EchoRequest.FromString,
                    response_serializer=stream_dot_v1_dot_stream__pb2.EchoResponse.SerializeToString,
            ),
            'EchoServerStream': grpc.unary_stream_rpc_method_handler(
                    servicer.EchoServerStream,
                    request_deserializer=stream_dot_v1_dot_stream__pb2.EchoRequest.FromString,
                    response_serializer=stream_dot_v1_dot_stream__pb2.EchoResponse.SerializeToString,
            ),
            'EchoBidirectionalStreamSync': grpc.stream_stream_rpc_method_handler(
                    servicer.EchoBidirectionalStreamSync,
                    request_deserializer=stream_dot_v1_dot_stream__pb2.EchoRequest.FromString,
                    response_serializer=stream_dot_v1_dot_stream__pb2.EchoResponse.SerializeToString,
            ),
            'EchoBidirectionalStreamAsync': grpc.stream_stream_rpc_method_handler(
                    servicer.EchoBidirectionalStreamAsync,
                    request_deserializer=stream_dot_v1_dot_stream__pb2.EchoRequest.FromString,
                    response_serializer=stream_dot_v1_dot_stream__pb2.EchoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.stream.v1.EchoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.stream.v1.EchoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EchoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EchoClientStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/api.stream.v1.EchoService/EchoClientStream',
            stream_dot_v1_dot_stream__pb2.EchoRequest.SerializeToString,
            stream_dot_v1_dot_stream__pb2.EchoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EchoServerStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/api.stream.v1.EchoService/EchoServerStream',
            stream_dot_v1_dot_stream__pb2.EchoRequest.SerializeToString,
            stream_dot_v1_dot_stream__pb2.EchoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EchoBidirectionalStreamSync(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/api.stream.v1.EchoService/EchoBidirectionalStreamSync',
            stream_dot_v1_dot_stream__pb2.EchoRequest.SerializeToString,
            stream_dot_v1_dot_stream__pb2.EchoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EchoBidirectionalStreamAsync(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/api.stream.v1.EchoService/EchoBidirectionalStreamAsync',
            stream_dot_v1_dot_stream__pb2.EchoRequest.SerializeToString,
            stream_dot_v1_dot_stream__pb2.EchoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
