# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api.v1 import service_pb2 as api_dot_v1_dot_service__pb2


class EchoAPIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HelloWorld = channel.unary_unary(
                '/api.v1.EchoAPI/HelloWorld',
                request_serializer=api_dot_v1_dot_service__pb2.EchoRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_service__pb2.EchoResponse.FromString,
                )
        self.WithError = channel.unary_unary(
                '/api.v1.EchoAPI/WithError',
                request_serializer=api_dot_v1_dot_service__pb2.EchoRequest.SerializeToString,
                response_deserializer=api_dot_v1_dot_service__pb2.EchoResponse.FromString,
                )


class EchoAPIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HelloWorld(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WithError(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EchoAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HelloWorld': grpc.unary_unary_rpc_method_handler(
                    servicer.HelloWorld,
                    request_deserializer=api_dot_v1_dot_service__pb2.EchoRequest.FromString,
                    response_serializer=api_dot_v1_dot_service__pb2.EchoResponse.SerializeToString,
            ),
            'WithError': grpc.unary_unary_rpc_method_handler(
                    servicer.WithError,
                    request_deserializer=api_dot_v1_dot_service__pb2.EchoRequest.FromString,
                    response_serializer=api_dot_v1_dot_service__pb2.EchoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.v1.EchoAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EchoAPI(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HelloWorld(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1.EchoAPI/HelloWorld',
            api_dot_v1_dot_service__pb2.EchoRequest.SerializeToString,
            api_dot_v1_dot_service__pb2.EchoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WithError(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.v1.EchoAPI/WithError',
            api_dot_v1_dot_service__pb2.EchoRequest.SerializeToString,
            api_dot_v1_dot_service__pb2.EchoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
