# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/stream/v1/stream.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'api/stream/v1/stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61pi/stream/v1/stream.proto\x12\rapi.stream.v1\"\x1e\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0c\x45\x63hoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xe4\x02\n\x0b\x45\x63hoService\x12M\n\x10\x45\x63hoClientStream\x12\x1a.api.stream.v1.EchoRequest\x1a\x1b.api.stream.v1.EchoResponse(\x01\x12M\n\x10\x45\x63hoServerStream\x12\x1a.api.stream.v1.EchoRequest\x1a\x1b.api.stream.v1.EchoResponse0\x01\x12Z\n\x1b\x45\x63hoBidirectionalStreamSync\x12\x1a.api.stream.v1.EchoRequest\x1a\x1b.api.stream.v1.EchoResponse(\x01\x30\x01\x12[\n\x1c\x45\x63hoBidirectionalStreamAsync\x12\x1a.api.stream.v1.EchoRequest\x1a\x1b.api.stream.v1.EchoResponse(\x01\x30\x01\x42\x34Z2github.com/easyp-tech/easyp-demo/pkg/api/stream/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.stream.v1.stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/easyp-tech/easyp-demo/pkg/api/stream/v1'
  _globals['_ECHOREQUEST']._serialized_start=45
  _globals['_ECHOREQUEST']._serialized_end=75
  _globals['_ECHORESPONSE']._serialized_start=77
  _globals['_ECHORESPONSE']._serialized_end=108
  _globals['_ECHOSERVICE']._serialized_start=111
  _globals['_ECHOSERVICE']._serialized_end=467
# @@protoc_insertion_point(module_scope)
