# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/web/v1/web.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'api/web/v1/web.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61pi/web/v1/web.proto\x12\x0fyour.service.v1\x1a\x1cgoogle/api/annotations.proto\"\x1e\n\rStringMessage\x12\r\n\x05value\x18\x01 \x01(\t2\xe8\x01\n\x0bYourService\x12\x63\n\x04\x45\x63ho\x12\x1e.your.service.v1.StringMessage\x1a\x1e.your.service.v1.StringMessage\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x10/v1/example/echo:\x01*\x12t\n\nEchoStream\x12\x1e.your.service.v1.StringMessage\x1a\x1e.your.service.v1.StringMessage\"\"\x82\xd3\xe4\x93\x02\x1c\"\x17/v1/example/echo/stream:\x01*(\x01\x30\x01\x42\x36Z4github.com/yourorg/yourprotos/gen/go/your/service/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.web.v1.web_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/yourorg/yourprotos/gen/go/your/service/v1'
  _globals['_YOURSERVICE'].methods_by_name['Echo']._loaded_options = None
  _globals['_YOURSERVICE'].methods_by_name['Echo']._serialized_options = b'\202\323\344\223\002\025\"\020/v1/example/echo:\001*'
  _globals['_YOURSERVICE'].methods_by_name['EchoStream']._loaded_options = None
  _globals['_YOURSERVICE'].methods_by_name['EchoStream']._serialized_options = b'\202\323\344\223\002\034\"\027/v1/example/echo/stream:\001*'
  _globals['_STRINGMESSAGE']._serialized_start=71
  _globals['_STRINGMESSAGE']._serialized_end=101
  _globals['_YOURSERVICE']._serialized_start=104
  _globals['_YOURSERVICE']._serialized_end=336
# @@protoc_insertion_point(module_scope)
