# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/service.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'api/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61pi/service.proto\x12\x03\x61pi\"\x1d\n\x0b\x43ustomError\x12\x0e\n\x06reason\x18\x01 \x01(\t\"\x1e\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0c\x45\x63hoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2v\n\x0b\x45\x63hoService\x12\x33\n\nHelloWorld\x12\x10.api.EchoRequest\x1a\x11.api.EchoResponse\"\x00\x12\x32\n\tWithError\x12\x10.api.EchoRequest\x1a\x11.api.EchoResponse\"\x00\x42*Z(github.com/easyp-tech/easyp-demo/pkg/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/easyp-tech/easyp-demo/pkg/api'
  _globals['_CUSTOMERROR']._serialized_start=26
  _globals['_CUSTOMERROR']._serialized_end=55
  _globals['_ECHOREQUEST']._serialized_start=57
  _globals['_ECHOREQUEST']._serialized_end=87
  _globals['_ECHORESPONSE']._serialized_start=89
  _globals['_ECHORESPONSE']._serialized_end=120
  _globals['_ECHOSERVICE']._serialized_start=122
  _globals['_ECHOSERVICE']._serialized_end=240
# @@protoc_insertion_point(module_scope)
